FROM centos:latest

#COPY project-folder app
# Setting Maven Version that needs to be installed
ARG MAVEN_VERSION=3.6.3

RUN echo ----------------------------------- Installing OpenJDK 8 ------------------------------
RUN dnf install -y unzip python3 python3-pip make java-1.8.0-openjdk which java-1.8.0-openjdk-devel wget jq

# Maven
RUN curl -fsSL https://archive.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz | tar xzf - -C /usr/share \
  && mv /usr/share/apache-maven-$MAVEN_VERSION /usr/share/maven \
  && ln -s /usr/share/maven/bin/mvn /usr/bin/mvn

ENV MAVEN_VERSION=${MAVEN_VERSION} && \
    M2_HOME /usr/share/maven && \
    maven.home $M2_HOME && \
    M2 $M2_HOME/bin && \
    PATH $M2:$PATH             

COPY nba app
RUN cd app && \
    mvn clean install && \
    cd .. && \
    rm -rf app 

RUN echo ------------------------------------ check versions ----------------------------------------------
ENV JAVA_HOME=/usr/lib/jvm/java
RUN java -version && \
    mvn -version
